### ISSUE TITLE
npm run dev出现编译错误，是什么导致的

### ISSUE THREAD

**Issue by zhoulvming** [liuzhenangel/v2ex#1]
ERROR in ENOENT: no such file or directory, scandir '/Users/zhoulvming/code/exper/vue-project/v2ex_frontend-master/node_modules/node-sass/vendor'
 @ ./~/vue-style-loader!./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js!./~/sass-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/App.vue 4:14-250 13:2-17:4 14:20-256

**Comment by liuzhenangel** [comment]
@zhoulvming 你执行了 `npm install` 了吗?

**Comment by zhoulvming** [comment]
执行了。貌似是sass loader出问题的

**Comment by liuzhenangel** [comment]
@zhoulvming  

``` bash
npm update
npm install
nodejs node_modules/node-sass/scripts/install.js
npm rebuild node-sass
```

https://github.com/sass/node-sass/issues/1579

你试一下这几条命令看能不能解决.

**Comment by zhoulvming** [comment]
刚准备回复呢，确实找到了跟你一样的解决方案，不过只要npm rebuild node-sass就够了。我是通过一个meteor项目发现的，错误提示如下：

Node Sass could not find a binding for your current environment: OS X 64-bit with Node 0.10.x

Found bindings for the following environments:
- OS X 64-bit with Node.js 6.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
