### ISSUE TITLE
关于api接口

### ISSUE THREAD

**Issue by zhoulvming** [liuzhenangel/v2ex#2]
你的数据来源是v2ex开放的api接口返回的数据，请问下是否还能做 知乎、SegmentFault、推酷等返回的数据，有了解过么

**Comment by liuzhenangel** [comment]
如果这几个网站提供了开放api都能做啊.

**Comment by zhoulvming** [comment]
知乎好像提供了，推酷找不到，没有的话可以用爬虫试试
