### ISSUE TITLE
关于api接口代码问题

### ISSUE THREAD

**Issue by zhoulvming** [liuzhenangel/v2ex#3]
在 Index.vue中， 获取最新数据是调用下面这样的代码：

this.$http.get('/api/topics/latest.json').then(function (response) {

请问 它如何拼接上 https://www.v2ex.com域名的，没看懂代码

**Comment by liuzhenangel** [comment]
@zhoulvming config/index.js 文件配置代理了.

先看看文档, 上面都有的.

**Comment by zhoulvming** [comment]
恩。看明白了
