### ISSUE TITLE
很迷惑的是，代码中找不到 给 topics 变量赋值的地方， 请指教

### ISSUE THREAD

**Issue by zhoulvming** [liuzhenangel/v2ex#4]
Index.vue中， 循环 渲染 数据代码：

<div class='line' v-for='topic in topics'>

我很迷惑的是，代码中找不到 给 topics 变量赋值的地方， 请指教

**Comment by liuzhenangel** [comment]
这个和vue-paginate这个package包有关系, 你看看.

**Comment by zhoulvming** [comment]
谢谢，果然在源代码中有描述到
