### ISSUE TITLE
dependencies missing

### ISSUE THREAD

**Issue by yuanshanxiaoni** [liuzhenangel/v2ex#5]
`npm install vue-paginate --save`

**Comment by liuzhenangel** [comment]
@poornigga
vue-paginate not support vue.js 2.0, I removed it.

**Comment by liuzhenangel** [comment]
@poornigga 

https://github.com/liuzhenangel/v2ex_frontend/commit/bd3f4dac323bb69e2f8adf0ec2acd91e8d635c56
