### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by ruixiu** [liuzhenangel/v2ex#8]
代码和Demo网站不同步吧？执行npm run dev报错：
ERROR in ./src/client-entry.js
Module build failed: Error: The node API for `babel` has been moved to `babel-core`.

请问是做么原因呢？

**Comment by dgo2dance** [comment]
同样的问题 ，求解  ，请问什么原因

**Comment by liuzhenangel** [comment]
@ruixiu @duanshuyong0 你们都是windows的系统吗？
