### ISSUE TITLE
怎么拿到用户回复的数据的？

### ISSUE THREAD

**Issue by ladieman217** [liuzhenangel/v2ex#9]
主题下用户回复的数据怎么拿到的，我怎么在v2ex的api里没有找到

**Comment by liuzhenangel** [comment]
v2ex api: https://gist.github.com/fanzeyi/6951803, https://www.v2ex.com/p/7v9TEc53

**Comment by liuzhenangel** [comment]
replies/show.json

URL: http://www.v2ex.com/api/replies/show.json

参数

topic_id - Topic ID
返回值

id - Reply ID
content - Reply 内容
content_rendered - 渲染过的 Reply 内容（比如 gist, Youtube 等）
thank - 感谢数量

**Comment by ladieman217** [comment]
新手弱弱的问一句，本地开发localhost跨域请求不到数据啊，请问怎么解决的...

**Comment by liuzhenangel** [comment]
vue.js 框架有提供跨域配置： https://github.com/liuzhenangel/v2ex_frontend/blob/master/config/index.js

发布后在https://github.com/liuzhenangel/v2ex_frontend/blob/master/config/nginx.config 里修改跨域配置。

**Comment by YUFENGWANG** [comment]
npm run dev 报错，win10系统 node v6.7.0 npm v4.0.3  
![Uploading U7%FZ)RR)6RQ}Z2BH[ZFY{J.png…]()

**Comment by ladieman217** [comment]
npm run dev 报错，win10系统 node v6.7.0 npm v4.0.3
![u7 fz rr 6rq z2bh zfy j](https://cloud.githubusercontent.com/assets/12859005/23004989/9bb1aa4c-f434-11e6-85eb-89a5493fb2da.png)

**Comment by ladieman217** [comment]
@liuzhenangel

**Comment by liuzhenangel** [comment]
@YUFENGWANG 帮不了你。。。一点解决问题的能力都不具备的话， 建议你先不要学习这个项目。
